// src/components/SemanticHead.tsx
import React from "react";
import { useSemanticPage } from "../core";
import { toJsonLdScript } from "../outputs/jsonld";

export interface SemanticHeadProps {
  /** Base URL for JSON-LD (e.g. "https://yoursite.com") */
  baseUrl?: string;
}

/**
 * Injects a <script type="application/ld+json"> into <head>
 * with the current semantic state. Updates automatically.
 */
export function SemanticHead({ baseUrl }: SemanticHeadProps) {
  const page = useSemanticPage();
  const jsonLd = toJsonLdScript(page, { baseUrl });

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: jsonLd }}
    />
  );
}

// packages/svelte/src/lib/components/SemanticHead.svelte
<script lang="ts">
  import { toJsonLdScript } from "@semant/core";
  import { useSemanticPage } from "../context.svelte.js";

  interface Props {
    baseUrl?: string;
  }

  let { baseUrl }: Props = $props();

  const page = useSemanticPage();

  const jsonLd = $derived(toJsonLdScript(page.current, { baseUrl }));
</script>

<svelte:head>
  <meta name="semant" content="0.1.0" />
  {@html `<script type="application/ld+json">${jsonLd}</script>`}
</svelte:head>
