// src/components/SemanticTextInput.tsx
import React from "react";
import { useSemantic } from "../core";

export interface SemanticTextInputProps {
  name: string;
  label: string;
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
  type?: "text" | "email" | "tel" | "url" | "number";
  description?: string;
  className?: string;
}

export function SemanticTextInput({
  name,
  label,
  value,
  onChange,
  placeholder,
  type = "text",
  description,
  className,
}: SemanticTextInputProps) {
  useSemantic({
    role: "Field",
    title: label,
    fields: [
      {
        key: name,
        label,
        type: type === "number" ? "number" : "text",
        value,
        description,
        set: (v) => onChange(String(v)),
      },
    ],
  });

  return (
    <div className={className}>
      <input
        type={type}
        value={value}
        placeholder={placeholder ?? label}
        onChange={(e) => onChange(e.target.value)}
      />
    </div>
  );
}

// packages/svelte/src/lib/components/SemanticTextInput.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { useSemantic } from "../context.svelte.js";

  interface Props {
    name: string;
    label: string;
    value: string;
    placeholder?: string;
    type?: "text" | "email" | "tel" | "url" | "number";
    description?: string;
    class?: string;
    onchange?: (value: string) => void;
    children?: Snippet<[{ value: string; onChange: (value: string) => void; placeholder?: string }]>;
  }

  let { name, label, value, placeholder, type = "text", description, class: className, onchange, children }: Props = $props();

  useSemantic(() => ({
    role: "Field",
    title: label,
    fields: [
      {
        key: name,
        label,
        type: type === "number" ? "number" : "text",
        value,
        description,
        set: (v) => onchange?.(String(v)),
      },
    ],
  }));
</script>

{#if children}
  {@render children({ value, onChange: (v) => onchange?.(v), placeholder })}
{:else}
  <div class={className}>
    <input
      {type}
      {value}
      placeholder={placeholder ?? label}
      oninput={(e) => onchange?.((e.target as HTMLInputElement).value)}
    />
  </div>
{/if}
