// packages/react/src/components/SemanticDatePicker.tsx
import React from "react";
import { useSemantic } from "../context";

export interface SemanticDatePickerProps {
  name: string;
  label: string;
  value: string | null;
  onChange: (date: string) => void;
  min?: string;
  max?: string;
  description?: string;
  className?: string;
  children?: (props: {
    value: string | null;
    select: (date: string) => void;
    min?: string;
    max?: string;
  }) => React.ReactNode;
}

export function SemanticDatePicker({
  name,
  label,
  value,
  onChange,
  min,
  max,
  description,
  className,
  children,
}: SemanticDatePickerProps) {
  useSemantic({
    role: "Field",
    title: label,
    fields: [
      {
        key: name,
        label,
        type: "date",
        value,
        constraints: { min, max },
        description: description ?? `Date range: ${min ?? "any"} to ${max ?? "any"}`,
        set: (v) => onChange(String(v)),
      },
    ],
  });

  if (children) {
    return <>{children({ value, select: onChange, min, max })}</>;
  }

  return (
    <div className={className}>
      <input
        type="date"
        value={value ?? ""}
        min={min}
        max={max}
        onChange={(e) => onChange(e.target.value)}
      />
    </div>
  );
}

// packages/svelte/src/lib/components/SemanticDatePicker.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { useSemantic } from "../context.svelte.js";

  interface Props {
    name: string;
    label: string;
    value?: string | null;
    min?: string;
    max?: string;
    description?: string;
    class?: string;
    onchange?: (date: string) => void;
    children?: Snippet<[{ value: string | null; select: (d: string) => void; min?: string; max?: string }]>;
  }

  let { name, label, value = null, min, max, description, class: className, onchange, children }: Props = $props();

  useSemantic(() => ({
    role: "Field",
    title: label,
    fields: [
      {
        key: name,
        label,
        type: "date",
        value,
        constraints: { min, max },
        description: description ?? `Date range: ${min ?? "any"} to ${max ?? "any"}`,
        set: (v) => onchange?.(String(v)),
      },
    ],
  }));
</script>

{#if children}
  {@render children({ value, select: (d) => onchange?.(d), min, max })}
{:else}
  <div class={className}>
    <input type="date" value={value ?? ""} {min} {max} onchange={(e) => onchange?.((e.target as HTMLInputElement).value)} />
  </div>
{/if}
