// packages/react/src/components/SemanticSelect.tsx
import React from "react";
import { useSemantic } from "../context";

export interface SemanticSelectProps {
  /** Field key used in AI commands, e.g. "party_size" */
  name: string;
  /** Human-readable label */
  label: string;
  /** Available options */
  options: Array<{ value: string | number; label: string }>;
  /** Current value */
  value: string | number | null;
  /** Change handler */
  onChange: (value: string | number) => void;
  /** AI-facing description */
  description?: string;
  /** Custom className */
  className?: string;
  /** Render prop for full custom rendering */
  children?: (props: {
    options: Array<{ value: string | number; label: string }>;
    selected: string | number | null;
    select: (value: string | number) => void;
  }) => React.ReactNode;
}

export function SemanticSelect({
  name,
  label,
  options,
  value,
  onChange,
  description,
  className,
  children,
}: SemanticSelectProps) {
  useSemantic({
    role: "Field",
    title: label,
    fields: [
      {
        key: name,
        label,
        type: "select",
        value,
        constraints: { options: options.map((o) => o.value) },
        description,
        set: (v) => onChange(v as string | number),
      },
    ],
  });

  if (children) {
    return <>{children({ options, selected: value, select: onChange })}</>;
  }

  return (
    <div className={className}>
      <select
        value={value ?? ""}
        onChange={(e) => {
          const num = Number(e.target.value);
          onChange(Number.isNaN(num) ? e.target.value : num);
        }}
      >
        <option value="" disabled>
          {label}
        </option>
        {options.map((opt) => (
          <option key={opt.value} value={opt.value}>
            {opt.label}
          </option>
        ))}
      </select>
    </div>
  );
}

// packages/svelte/src/lib/components/SemanticSelect.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { useSemantic } from "../context.svelte.js";

  interface Props {
    name: string;
    label: string;
    options: Array<{ value: string | number; label: string }>;
    value?: string | number | null;
    description?: string;
    class?: string;
    onchange?: (value: string | number) => void;
    children?: Snippet<[{ options: Props["options"]; selected: Props["value"]; select: (v: string | number) => void }]>;
  }

  let { name, label, options, value = null, description, class: className, onchange, children }: Props = $props();

  useSemantic(() => ({
    role: "Field",
    title: label,
    fields: [
      {
        key: name,
        label,
        type: "select",
        value,
        constraints: { options: options.map((o) => o.value) },
        description,
        set: (v) => onchange?.(v as string | number),
      },
    ],
  }));

  function handleChange(e: Event) {
    const raw = (e.target as HTMLSelectElement).value;
    const num = Number(raw);
    onchange?.(Number.isNaN(num) ? raw : num);
  }
</script>

{#if children}
  {@render children({ options, selected: value, select: (v) => onchange?.(v) })}
{:else}
  <div class={className}>
    <select value={value ?? ""} onchange={handleChange}>
      <option value="" disabled>{label}</option>
      {#each options as opt (opt.value)}
        <option value={opt.value}>{opt.label}</option>
      {/each}
    </select>
  </div>
{/if}
