// packages/svelte/src/lib/components/SemanticInfo.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { useSemantic } from "../context.svelte.js";

  interface Props {
    role: string;
    title?: string;
    description?: string;
    meta?: Record<string, unknown>;
    order?: number;
    class?: string;
    children?: Snippet;
  }

  let { role, title, description, meta, order, class: className, children }: Props = $props();

  useSemantic(() => ({
    role,
    title,
    description,
    meta,
    fields: [],
    order,
  }));
</script>

<div class={className}>
  {#if children}
    {@render children()}
  {/if}
</div>

// packages/react/src/components/SemanticInfo.tsx
import React from "react";
import { useSemantic } from "../context";

export interface SemanticInfoProps {
  /** Semantic role, e.g. "restaurant", "product", "article" */
  role: string;
  title?: string;
  description?: string;
  /** Key-value metadata — all of this becomes AI-readable */
  meta?: Record<string, unknown>;
  order?: number;
  children?: React.ReactNode;
  className?: string;
}

/**
 * A non-interactive semantic block. Use it to expose static
 * information (restaurant details, product specs, etc.) to AI.
 */
export function SemanticInfo({
  role,
  title,
  description,
  meta,
  order,
  children,
  className,
}: SemanticInfoProps) {
  useSemantic({
    role,
    title,
    description,
    meta,
    fields: [],
    order,
  });

  return <div className={className}>{children}</div>;
}
