// packages/svelte/src/lib/components/SemanticSlider.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { useSemantic } from "../context.svelte.js";

  interface Props {
    name: string;
    label: string;
    value: number;
    min: number;
    max: number;
    step?: number;
    description?: string;
    class?: string;
    onchange?: (value: number) => void;
    children?: Snippet<[{ value: number; set: (v: number) => void; min: number; max: number; step: number }]>;
  }

  let { name, label, value, min, max, step = 1, description, class: className, onchange, children }: Props = $props();

  useSemantic(() => ({
    role: "Field",
    title: label,
    fields: [
      {
        key: name,
        label,
        type: "slider",
        value,
        constraints: { min, max, step },
        description,
        set: (v) => onchange?.(Number(v)),
      },
    ],
  }));
</script>

{#if children}
  {@render children({ value, set: (v) => onchange?.(v), min, max, step })}
{:else}
  <div class={className}>
    <label>
      {label}: {value}
      <input type="range" {min} {max} {step} {value} oninput={(e) => onchange?.(Number((e.target as HTMLInputElement).value))} />
    </label>
  </div>
{/if}

// packages/react/src/components/SemanticSlider.tsx
import React from "react";
import { useSemantic } from "../context";

export interface SemanticSliderProps {
  /** Field key used in AI commands */
  name: string;
  /** Human-readable label */
  label: string;
  /** Current value */
  value: number;
  /** Change handler */
  onChange: (value: number) => void;
  /** Minimum value */
  min: number;
  /** Maximum value */
  max: number;
  /** Step increment (default 1) */
  step?: number;
  /** AI-facing description */
  description?: string;
  /** Custom className */
  className?: string;
  /** Render prop for full custom rendering */
  children?: (props: {
    value: number;
    set: (v: number) => void;
    min: number;
    max: number;
    step: number;
  }) => React.ReactNode;
}

export function SemanticSlider({
  name,
  label,
  value,
  onChange,
  min,
  max,
  step = 1,
  description,
  className,
  children,
}: SemanticSliderProps) {
  useSemantic({
    role: "Field",
    title: label,
    fields: [
      {
        key: name,
        label,
        type: "slider",
        value,
        constraints: { min, max, step },
        description,
        set: (v) => onChange(Number(v)),
      },
    ],
  });

  if (children) {
    return <>{children({ value, set: onChange, min, max, step })}</>;
  }

  return (
    <div className={className}>
      <label>
        {label}: {value}
        <input
          type="range"
          min={min}
          max={max}
          step={step}
          value={value}
          onChange={(e) => onChange(Number(e.target.value))}
        />
      </label>
    </div>
  );
}
