// packages/svelte/src/lib/components/SemanticCheckbox.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { useSemantic } from "../context.svelte.js";

  interface Props {
    name: string;
    label: string;
    checked: boolean;
    description?: string;
    class?: string;
    onchange?: (checked: boolean) => void;
    children?: Snippet<[{ checked: boolean; set: (value: boolean) => void }]>;
  }

  let { name, label, checked, description, class: className, onchange, children }: Props = $props();

  useSemantic(() => ({
    role: "Field",
    title: label,
    fields: [
      {
        key: name,
        label,
        type: "checkbox",
        value: checked,
        description,
        set: (v) => onchange?.(v === true || v === "true" || v === 1),
      },
    ],
  }));
</script>

{#if children}
  {@render children({ checked, set: (v) => onchange?.(v) })}
{:else}
  <div class={className}>
    <label>
      <input type="checkbox" {checked} onchange={() => onchange?.(!checked)} />
      {label}
    </label>
  </div>
{/if}

// packages/react/src/components/SemanticCheckbox.tsx
import React from "react";
import { useSemantic } from "../context";

export interface SemanticCheckboxProps {
  /** Field key used in AI commands */
  name: string;
  /** Human-readable label */
  label: string;
  /** Current checked state */
  checked: boolean;
  /** Change handler */
  onChange: (checked: boolean) => void;
  /** AI-facing description */
  description?: string;
  /** Custom className */
  className?: string;
  /** Render prop for full custom rendering */
  children?: (props: {
    checked: boolean;
    set: (value: boolean) => void;
  }) => React.ReactNode;
}

export function SemanticCheckbox({
  name,
  label,
  checked,
  onChange,
  description,
  className,
  children,
}: SemanticCheckboxProps) {
  useSemantic({
    role: "Field",
    title: label,
    fields: [
      {
        key: name,
        label,
        type: "checkbox",
        value: checked,
        description,
        set: (v) => onChange(v === true || v === "true" || v === 1),
      },
    ],
  });

  if (children) {
    return <>{children({ checked, set: onChange })}</>;
  }

  return (
    <div className={className}>
      <label>
        <input
          type="checkbox"
          checked={checked}
          onChange={() => onChange(!checked)}
        />
        {` ${label}`}
      </label>
    </div>
  );
}
