// packages/svelte/src/lib/components/SemanticMultiSelect.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { useSemantic } from "../context.svelte.js";

  interface Props {
    name: string;
    label: string;
    options: Array<{ value: string | number; label: string }>;
    value: Array<string | number>;
    description?: string;
    class?: string;
    onchange?: (value: Array<string | number>) => void;
    children?: Snippet<[{ options: Props["options"]; selected: Array<string | number>; toggle: (v: string | number) => void }]>;
  }

  let { name, label, options, value, description, class: className, onchange, children }: Props = $props();

  function toggle(v: string | number) {
    if (value.includes(v)) {
      onchange?.(value.filter((x) => x !== v));
    } else {
      onchange?.([...value, v]);
    }
  }

  useSemantic(() => ({
    role: "Field",
    title: label,
    fields: [
      {
        key: name,
        label,
        type: "multi-select",
        value,
        constraints: { options: options.map((o) => o.value) },
        description,
        set: (v) => {
          if (typeof v === "string") {
            try {
              const parsed = JSON.parse(v);
              if (Array.isArray(parsed)) { onchange?.(parsed); return; }
            } catch { /* not JSON */ }
            onchange?.([v]);
            return;
          }
          if (Array.isArray(v)) {
            onchange?.(v as Array<string | number>);
          } else {
            onchange?.([v as string | number]);
          }
        },
      },
    ],
  }));
</script>

{#if children}
  {@render children({ options, selected: value, toggle })}
{:else}
  <fieldset class={className}>
    <legend>{label}</legend>
    {#each options as opt (opt.value)}
      <label>
        <input type="checkbox" checked={value.includes(opt.value)} onchange={() => toggle(opt.value)} />
        {opt.label}
      </label>
    {/each}
  </fieldset>
{/if}

// packages/react/src/components/SemanticMultiSelect.tsx
import React from "react";
import { useSemantic } from "../context";

export interface SemanticMultiSelectProps {
  /** Field key used in AI commands */
  name: string;
  /** Human-readable label */
  label: string;
  /** Available options */
  options: Array<{ value: string | number; label: string }>;
  /** Currently selected values */
  value: Array<string | number>;
  /** Change handler */
  onChange: (value: Array<string | number>) => void;
  /** AI-facing description */
  description?: string;
  /** Custom className */
  className?: string;
  /** Render prop for full custom rendering */
  children?: (props: {
    options: Array<{ value: string | number; label: string }>;
    selected: Array<string | number>;
    toggle: (value: string | number) => void;
  }) => React.ReactNode;
}

export function SemanticMultiSelect({
  name,
  label,
  options,
  value,
  onChange,
  description,
  className,
  children,
}: SemanticMultiSelectProps) {
  const toggle = (v: string | number) => {
    if (value.includes(v)) {
      onChange(value.filter((x) => x !== v));
    } else {
      onChange([...value, v]);
    }
  };

  useSemantic({
    role: "Field",
    title: label,
    fields: [
      {
        key: name,
        label,
        type: "multi-select",
        value,
        constraints: { options: options.map((o) => o.value) },
        description,
        set: (v) => {
          // AI sends JSON array string or single value
          if (typeof v === "string") {
            try {
              const parsed = JSON.parse(v);
              if (Array.isArray(parsed)) {
                onChange(parsed);
                return;
              }
            } catch {
              // not JSON, treat as single value
            }
          }
          if (Array.isArray(v)) {
            onChange(v as Array<string | number>);
          } else {
            toggle(v as string | number);
          }
        },
      },
    ],
  });

  if (children) {
    return <>{children({ options, selected: value, toggle })}</>;
  }

  return (
    <fieldset className={className}>
      <legend>{label}</legend>
      {options.map((opt) => (
        <label key={opt.value}>
          <input
            type="checkbox"
            checked={value.includes(opt.value)}
            onChange={() => toggle(opt.value)}
          />
          {` ${opt.label}`}
        </label>
      ))}
    </fieldset>
  );
}
